# Generated by Django 5.0.4 on 2024-04-17 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="shoppingcart",
            old_name="user_id",
            new_name="user",
        ),
    ]
